// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSnapshot():Promise<main.Snapshot>;

export function HideWindow():Promise<void>;

export function SaveConnection(arg1:main.ConnectionSettings):Promise<main.Snapshot>;

export function SetServiceAutoStart(arg1:boolean):Promise<main.Snapshot>;

export function SetSilentStart(arg1:boolean):Promise<main.Snapshot>;

export function ToggleProxy(arg1:main.ConnectionSettings):Promise<main.Snapshot>;

export function ToggleService():Promise<main.Snapshot>;

export function ValidateConnection(arg1:main.ConnectionSettings):Promise<main.Snapshot>;
