// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SetServiceAutoStart(arg1) {
  return window['go']['main']['App']['SetServiceAutoStart'](arg1);
}

export function SetSilentStart(arg1) {
  return window['go']['main']['App']['SetSilentStart'](arg1);
}

export function ToggleProxy(arg1) {
  return window['go']['main']['App']['ToggleProxy'](arg1);
}

export function ToggleService() {
  return window['go']['main']['App']['ToggleService']();
}

export function ValidateConnection(arg1) {
  return window['go']['main']['App']['ValidateConnection'](arg1);
}
